version: '3.8'

services:
  momo-store-front:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    stdin_open: true
    tty: true

volumes:
  node_modules:
