# Build stage
FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Deploy stage
FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY /docker/nginx.conf /etc/nginx/nginx.conf

COPY /docker/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
